export const BUY_TOKENS_BEGIN = 'BUY_TOKENS_BEGIN';
export const BUY_TOKENS_SUCCESS = 'BUY_TOKENS_SUCCESS';
export const BUY_TOKENS_FAILURE = 'BUY_TOKENS_FAILURE';
export const FETCH_APPROVAL_BEGIN = 'FETCH_APPROVAL_BEGIN'
export const FETCH_APPROVAL_SUCCESS = 'FETCH_APPROVAL_SUCCESS'
export const FETCH_APPROVAL_FAILURE = 'FETCH_APPROVAL_FAILURE'
export const FETCH_HAS_APPROVED_BEGIN = 'FETCH_HAS_APPROVED_BEGIN'
export const FETCH_HAS_APPROVED_SUCCESS = 'FETCH_HAS_APPROVED_SUCCESS'
export const FETCH_HAS_APPROVED_FAILURE = 'FETCH_HAS_APPROVED_FAILURE'

